// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entry "github.com/edwardfernando/godiary/entry"
import errorwrapper "github.com/edwardfernando/godiary/errorwrapper"
import mock "github.com/stretchr/testify/mock"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// PostEntry provides a mock function with given fields: request
func (_m *Usecase) PostEntry(request entry.PostEntryRequest) *errorwrapper.ErrWrapper {
	ret := _m.Called(request)

	var r0 *errorwrapper.ErrWrapper
	if rf, ok := ret.Get(0).(func(entry.PostEntryRequest) *errorwrapper.ErrWrapper); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errorwrapper.ErrWrapper)
		}
	}

	return r0
}
